---
language: python

python:
    - '3.7'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
    - sudo apt-get update
    - sudo apt-get install sshpass

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/Denisfench/messaging

script:
    - make tests

# deploy to heroku
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: callahan-messaging
